# Generated by Django 3.1.2 on 2020-10-30 16:26

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssigned',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=50, null=True)),
                ('org_department', models.CharField(choices=[('COMPUTER', 'COMPUTER'), ('EXTC', 'EXTC'), ('MECHANICAL', 'MECHANICAL'), ('AUTOMOBILE', 'AUTOMOBILE')], max_length=50, null=True)),
                ('res_person', models.CharField(max_length=50, null=True)),
                ('res_person_profile_pic', models.ImageField(blank=True, null=True, upload_to='Resource Person/profile_pic/')),
                ('forwhome', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], max_length=50, null=True)),
                ('types', models.CharField(choices=[('Workshop', 'Workshop'), ('Seminar', 'Seminar')], max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name=accounts.models.Faculty)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('event_coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.faculty')),
            ],
            options={
                'verbose_name_plural': 'Task Assigned',
            },
        ),
    ]
