# Generated by Django 3.1.2 on 2020-10-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_taskassigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassigned',
            name='email',
        ),
    ]
