# Generated by Django 3.1.2 on 2020-10-31 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201030_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassigned',
            name='event_coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty'),
        ),
    ]
