# Generated by Django 3.1.2 on 2020-10-31 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201031_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassigned',
            name='types',
            field=models.CharField(choices=[('Workshop', 'Workshop'), ('Seminar', 'Seminar')], max_length=50),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(blank=True)),
                ('org_department', models.CharField(choices=[('COMPUTER', 'COMPUTER'), ('EXTC', 'EXTC'), ('MECHANICAL', 'MECHANICAL'), ('AUTOMOBILE', 'AUTOMOBILE')], max_length=50, null=True)),
                ('res_person', models.CharField(max_length=150)),
                ('res_person_profile_pic', models.ImageField(upload_to='Resource Person/Profile Pic/')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('types', models.CharField(choices=[('Workshop', 'Workshop'), ('Seminar', 'Seminar')], max_length=50)),
                ('forwhome', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], max_length=50, null=True)),
                ('no_participants', models.IntegerField(null=True)),
                ('remark', models.CharField(max_length=50, null=True)),
                ('p_link', models.URLField(null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('event_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty')),
                ('event_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.taskassigned')),
            ],
        ),
    ]
