# Generated by Django 3.1.2 on 2020-10-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201031_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterField(
            model_name='report',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='forwhome',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='no_participants',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='org_department',
            field=models.CharField(choices=[('COMPUTER', 'COMPUTER'), ('EXTC', 'EXTC'), ('MECHANICAL', 'MECHANICAL'), ('AUTOMOBILE', 'AUTOMOBILE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='p_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='remark',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='taskassigned',
            name='event_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='taskassigned',
            name='forwhome',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='taskassigned',
            name='org_department',
            field=models.CharField(choices=[('COMPUTER', 'COMPUTER'), ('EXTC', 'EXTC'), ('MECHANICAL', 'MECHANICAL'), ('AUTOMOBILE', 'AUTOMOBILE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='taskassigned',
            name='res_person',
            field=models.CharField(max_length=150),
        ),
    ]
