# Generated by Django 3.1.2 on 2020-11-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201031_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassigned',
            name='res_person_profile_pic',
        ),
    ]
