# Generated by Django 3.1.2 on 2020-11-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_taskassigned_res_person_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='academic_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='remark',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
