# Generated by Django 3.1.2 on 2020-11-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201113_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='res_person_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Resource Person/Profile Pic/'),
        ),
    ]
