# Generated by Django 3.1.2 on 2020-11-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201113_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='res_person_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Resource Person/Profile Pic/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
