# Generated by Django 3.1.2 on 2020-11-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201115_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='joined_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
